config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "mandalarts#index"
  resources :mandalarts

  get '/mindmaps', to: 'mindmaps#index'

  namespace :api, format: 'json' do
    resources :mindmaps
  end
  resources :users

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mandalart.rb
class Mandalart < ApplicationRecord
  $mandalart_blocks_num = 9

  validates :text, length: { maximum: 300 }
end

app/models/mindmap.rb
class Mindmap < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true,
                    length:   { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    length:     { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engin::MIN_COST : BCrypt::Engin.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/api/mindmaps_controller.rb
class Api::MindmapsController < ApplicationController
  def index
    @mindmaps = Mindmap.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/mandalarts_controller.rb
class MandalartsController < ApplicationController
  def index
    # 最初から配列の要素を9つ入れとく
    # 配列の要素の中身があれば、何もしない
    # 配列の要素の中身があれば、""の要素を入れとく

    @mandalarts = Mandalart.all

    if @mandalarts.count < $mandalart_blocks_num
      ($mandalart_blocks_num - @mandalarts.count).times do |_mandalart|
        Mandalart.create(text: '')
      end
      @mandalarts = Mandalart.all
    end
  end

  def new
    @mandalart = Mandalart.new
  end

  def create
    @mandalart = Mandalart.new(mandalart_params)
    if @mandalart.save
      redirect_to mandalarts_path
    else
      render 'new'
    end
  end

  def edit
    @mandalart = Mandalart.find(params[:id])
  end

  def update
    @mandalart = Mandalart.find(params[:id])
    if @mandalart.update(mandalart_params)
      redirect_to mandalarts_path, status: :moved_permanently
    else
      render 'edit'
    end
  end

  private

  def mandalart_params
    params.require(:mandalart).permit(:text)
  end
end

app/controllers/mindmaps_controller.rb
class MindmapsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    password = params[:session][:password]
    if user&.authenticate(password)
      log_in user
      redirect_to user
    else
      flash[:danger] = 'パスワードとemailの組み合わせが正しくありません'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/api/mindmaps_helper.rb
module Api::MindmapsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_error_messages(model, attribute)
    @error = nil
    # インスタンスの中身を一旦削除
    # 削除しないと2回目呼ばれたときに、インスタンスの中身を
    # そのまま使用してしまい、違うフォームで別のエラーメッセージが
    # 出力されてしまう。
    model.errors.full_messages_for(attribute).each do |error|
      @error = error
    end
    @error
  end
end

app/helpers/mandalarts_helper.rb
module MandalartsHelper
end

app/helpers/mindmaps_helper.rb
module MindmapsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    = yield

app/views/mandalarts/_form.html.haml
= form_with model: @mandalart ,class: "form-wrapper" do |f|
  = f.text_area :text , class: "form"
  = f.submit

app/views/mandalarts/edit.html.haml
= form_with model: @mandalart ,class: "form-wrapper" do |f|
  = f.text_area :text , class: "form"
  = f.submit

app/views/mandalarts/index.html.haml
%table.mandalart-table
  %tr
    - @mandalarts[0..2].each do |mandalart|
      %td
        .mandalart-text
          = mandalart.text
        = link_to "記入", edit_mandalart_path(mandalart.id)
  %tr
    - @mandalarts[3..5].each do |mandalart|
      %td
        .mandalart-text
          = mandalart.text
        = link_to "記入", edit_mandalart_path(mandalart.id)
  %tr
    - @mandalarts[6..8].each do |mandalart|
      %td
        .mandalart-text
          = mandalart.text
        = link_to "記入", edit_mandalart_path(mandalart.id)
= link_to "マインドマップ" , mindmaps_path

= link_to "ユーザー登録", new_user_path 

app/views/mandalarts/new.html.haml
= render "mandalarts/form"

app/views/mindmaps/index.html.haml
= javascript_pack_tag 'mindmaps'
= stylesheet_pack_tag 'mindmaps'

app/views/users/new.html.haml
= form_with(model: @user) do |f|
  %div
    = f.label :name
    = f.text_field :name
  %div
    = display_error_messages(@user,:name)
  %div
    = f.label :email
    = f.email_field :email
  %div
    = display_error_messages(@user,:email)
  %div
    = f.label :password
    = f.password_field :password
    %p 6字以上のパスワード
  %div
    = display_error_messages(@user,:password)
  %div
    %div
      = f.label :password_confirmation
    = f.password_field :password_confirmation
  %div
    = display_error_messages(@user,:password_confirmation)
  = f.submit "登録"

%p すでにアカウントをもっていますか？
= link_to "ログイン", "/login"

app/views/users/show.html.haml
= @user.name
= @user.password
- flash.each do |message_type,message|
  = message

= link_to  "ログアウト",logout_path, method: :delete